version: '3'
services:
  mysql:
    restart: always
    image: mysql:5.7.25
    container_name: xpowerdesign-mysql
    command: [
        'mysqld',
        '--innodb-buffer-pool-size=20M',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+8:00'
      ]
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: xpowerdesign
      MYSQL_USER: root
    ports:
      - "23306:3306"
    volumes:
      - xpowerdesign-mysql-data:/var/lib/mysql
    networks:
      - xpowerdesign-net

volumes:
  xpowerdesign-mysql-data:
    driver: local

networks:
  xpowerdesign-net:
    driver: bridge