management.endpoints.web.exposure.include: "*"


spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
  profiles:
    active: local
  flyway:
    enabled: true
    locations: classpath:/db/migrations
    baseline-on-migrate: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

logging:
  level:
    web: debug
    com:
      actuator:
        controller:
          ActuatorController: debug