spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:23306/xpowerdesign?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_bin&useServerPrepStmts=false&rewriteBatchedStatements=true
    username: root
    password: password

  devtools:
    add-properties: true

